Web mercator
agrc/fiber-verification pull request #51
Opened 2016-10-03 17:05 UTC by stdavis

Closes https://github.com/agrc/web-mercator-wsut-killer/issues/15 also.

2016-10-03 21:45 UTC, steveoh requested changes
this looks pretty good. 

nora says: zxxcvbnmmmmmmp1ppppppp

2016-10-03 21:45 UTC, steveoh commented on README.md
>  [production site](https://fiberediting.mapserv.utah.gov/map/)
this url is wrong. It should not contain the `map/`

2016-10-03 21:45 UTC, steveoh commented on src/app/config.js
> +        xhr(require.baseUrl + 'secrets.json', {
we should consider switching this to not be sync since that isn't going to be supported in the future.

2016-10-03 21:45 UTC, steveoh commented on src/app/config.js
> +    esriConfig.defaults.io.corsEnabledServers.push('mapserv.utah.gov');
we will probably want to add discover as well.

2016-10-03 21:45 UTC, steveoh commented on GruntFile.js
> +                commitFiles: bumpFiles.concat(['src/ChangeLog.html']),
this is nice for when you `grunt bump-only:x` update the change log and then `grunt bump-commit`.

2016-10-04 13:29 UTC, stdavis commented on GruntFile.js
> +                commitFiles: bumpFiles.concat(['src/ChangeLog.html']),
Not sure that I understand. Are you suggesting a change or just commenting? 

I just don't want to miss something.

2016-10-04 13:30 UTC, stdavis commented
@steveoh: I've addressed your comments in three commits.

2016-10-04 13:31 UTC, steveoh commented on GruntFile.js
> +                commitFiles: bumpFiles.concat(['src/ChangeLog.html']),
i think i might have read the diff backwards.

2016-10-04 13:32 UTC, steveoh approved these changes

2016-10-04 13:34 UTC, stdavis commented
Also, tell Nora the Explorer: 
📩💾🍃🍣🎨🎐🕧 🔲🌌🍆🌅👬 🍬📡🎏🔝🌊🍻👊 🌎🍵🌁🕗💑🏤 💻🎉💱🐢🐘 📊📮🌉🔜📡 👥🏈👣👏📦 🌶🍅🍟👉💴. 🎵📨🎋🐈🐲🐨 📘🍄🐾👆👸📄🔚 🔄🌒🗾📷🍴💾 🔦🌆💷📶🌽🐏 💆💌🍼💫💀 🔫🐮💖👕📝 🍶🐙🐠🏨 📙🔥🕣🔑👗💘🌞 💃🍬💾💦📹🎹👧 🏤🌎🎯🔥👊🕘 🌶💌🍙📜🏂🕧 📯🐱🍠🐃🐱🐈👟 🔠🍠🌜🕃🎧💐. 💖👶💢🍹 💅🎉📹🔵🐇🔆 🍄🌷🍉🍝🎃 📟🎄💄🐈🐠🔎 🎾📡🔣🔡🐲 🌴🔸🔄🕘👛💇 🔦🔻👗💾💊📭🐰 🎒🐹🏫👉🐛🍷 🍔🌲🔨📋🎑💤👔 🐺👛🔝📓👪🐒.
🎳👄🗾💂💀 💉🐹💗🐟🐑 🏫🔏👑💆 🍵🎰🐾🏁🔞🐃 🔭👟📃📧 📹🍺💙🔇🌲🔤🔥📣 🌷🐲🐐💠 💑🐱🍡🐓🎒 🍳👣🎶🕝🏥🔑🐌 🔠📛🍈🔣🐼🕚🌷 🎓🔞🏣🐤🔚🐖🌈 📀💗💈🌙💡🐧🐚🌀 🍷🍺💧🌱🍗 🎴🔝💛🎃🍋🐪🔺 🔙📚🎭👺💍🐞🐛 🐗📌🐷📄🎮. 📧👇🐘🍃🔸 📏🔍📵💬📱 🔴🏦👶🕗🐒🌻🐳 🍪🎴🐸🔌🎲👕 🔤🐏💐🌽💁🔁 🐒🍮🔹🌛🐳💚 👠🕑🐛🐥🍮🐄 💚🐤📰🌟🎼👼 💾👵🌚💒🐆 🎸🌏🍡👟💨 🐘🍊💺🏰🐭👪🐽🌲 🌇💰👞💣🔉💓🍛. 🍳💨👽👍🍳 🌱👃👱👠🍝 👽💚📨🎸 🎰💃👜📋🍯🐽 🎡🐈🎲🕠🔛🐧💷 🍦💲🌸🔻🔱 📅👥🔫🎭🍱 💯🎅📏👖👤🍚 💶🔞🔲🍋🎽 🎇📶🍫💉👤. 🍝🎓👀🔭🎂🔑🎂 💊🔑🔛🐓🔁🕥 🐛🔨🔣🕢🔴👿📉 👣💴🌀🐝🐪 💥📐💜👎🔜💂👘 🌔👇🎂🍥👏👬📆 💃🎠🔔📕🕡🍁💉 📌💮🌁💢👐 🎎🏠🍱👯📃 🔗👓💲🍈🎷 🌌🌾🌸💾📌💀 💎👌🍗🕔📕 🍁👋📹👀🐆🐷👢. 💢🔭📍🌂🕝🍦🌵 👹🐼🍯📃👳 🐶🌅💁🕞🎅🌀 🎥📭🐟🍏👲🐦 🎲👫💨💈🎭 👌🐦💢👊📜 👽🍌🌻👽📌🐂🍕🌘 🌆🌕🐪📹📰💈👿📅 🍠📼🕤📤 💀🐭🎦🍰📵 📍💻🌱🌙 🎂👙🏩📤🍵.
🎠👑🌰🏭🔪 👆🐤🍚📜💲 🐘👢🎷📥🔵🌘 🔣🍐📂🌅🍢🎨💷 🍑💟🌌🎵🍜 🏫📹🐙🌂💊🐎👿 🎳📪🔟🍝 🌘🐊🐗🌕🎿🍤📯 👦🐰👔🐽👏🎁🔶🌴 🔹👐📞🌀💠🍝🎉. 🕟📙🍊💝💥 🐙📒🎐🔏💸🎽🌻 👏🌺🎰🔣🐞🐼🎳 💬🔑🐽🎊🌵📻 🕚🍎🌱📉🐉🎩 📌📇👾🎮🍱🗾🔯💶 🐍🍪🎶🍕🏬👜 🐽🐇🎥📍🌇🐸💟 💉💾🎴📏📉🎾👆 🎬🔸🍸🔸📙 🔊🎯👆🕒💠📭 🌁📵💣🐓🍁 🐝🕒👈🕙 🕠💴🌐🕠👳 🔋🌽🐽🔥🔋🍡. 🎫🏠🕞📨🌒💕 💔🏣🍻📄🔜🕙 🎇🍼🔓🐑💐🔈 🐉🕀🎵🍊💩💵 📣🎺🎡🕁💨🐠 💃🎥📀💁🍴 🐍🐃💬🎊 💜👗👊💁🍃 📐🐖🎠🎄🔂 📘👪🍸🌗📶 🐤🍢💲🐡📤 🐚🏧🔐👲🏠💘 🌱💑🎐🎱 📲🎃🐶👤.
🔢💗💈🐉🐋 📫🕃🕚📼 🌚📊🍳🐊🐸💣🌓 🔘🍲🌹💑💩🎌 👯🌇🎵🎯 💟📒🐁🔥🎅💙 🍎👀📙💣🌑 📯🐣🎣📛👌 🎁📻🏂🎣🎅🔞 🐘🔙🕖👌🐾🐨 🍈🎥🍟🍳💹. 👶📺🐚📩 💦🍑👖🔝🌗🔥 🔌🎮📘🍂🎫 🍰📤👎🐹 💓🎁💎📬🌔🔊💐 🏇🐠📟🍲🌉💬 📆🔧👧📕💰🔇🕤🍅 💇📕🍸💁🐐🍣 🌺🔄👽🍊🌅🍚 🔅📓🌠📙🔋🍫🔒 📔🐤👉👭 🔋🎸🔍🔖 🐸🌶🔍🎫🏥 🍟🐘🔗🐨👦🐪 🔅🌁📑📦👵 🏊💈🍃🐣📞🎓🕢. 🗽🍼👴🎍🎡 🔏📉🌅🎼🔱🎂 🌇💺🔣🎾🎿🎣📣 📯📮🕖🍐🐸 💙🐐🌕🎲 📨🔼🕥🗽🕤 🎰🔯💦🐵 🎁🍱🌼🎇👊🐤🍳 📵🐰💤🌴🍐📎 📼🐮👎🎴🔆🍂 🎧👟🌎💞🌖 🕣🍴💼📙💅👄 🕓📕👔🐀🗽📳💼.

2016-10-04 13:38 UTC, steveoh commented
that fancy dojo!text failed the build :( So a try catch?

2016-10-04 13:39 UTC, stdavis commented
Hold on. I'm foo-barring this all up...

2016-10-04 14:27 UTC, stdavis commented
OK. Builds are passing again. I'll merge this now.

2016-10-04 14:28 UTC, merged